### ISSUE TITLE
Bpmn gateways 

### ISSUE THREAD

**Issue by Diaskhan** [elsa-workflows/elsa-designer#15]
Its possible to make fork and join as bpmn gateways ?
https://i.pinimg.com/564x/3e/13/d5/3e13d57ea9f12d2760b7ca339bac3bba.jpg

By the way could u give answer ? 
There have possibility to flow conditional flow ? 
1. Parralel gateway ?
2. Or gateway ( flow element by some condition )?

Businnes Analysyst love bpmn because its simple to explain.

Please explore bpmn standart! 
In my opinion all worflow system and state machines comes to bpmn standart !

**Comment by Diaskhan** [comment]
https://theartfulmodellerdotcom.files.wordpress.com/2015/11/big-process-model.png

Business proccese could be very huge. If re planing to do popular system. Better borrow some icons of bpmn standart. Not trying to say implement bpmn 2.0. just borrow some ideas and concepts !

**Comment by sfmskywalker** [comment]
Although Elsa doesn't implement BPMN at the moment, it does support parallel execution (in the form of the `Fork` activity) and "Or" execution (in the form of the `IfElse` activity).

There's an [existing issue](https://github.com/elsa-workflows/elsa-core/issues/39) asking for the same (implementing BPMN).
